### ISSUE TITLE
Wiki: Links in Home page not correct

### ISSUE THREAD

**Issue by verhagen** [awltech/sonar-data-migrator#3]
On the [_Home_](https://github.com/awltech/sonar-data-migrator/wiki) page there are 3 links at the bottum, which reference to incorrect links.

**Example** current one of the links is
https://github.com/awltech/sonar-data-migrator/wiki/Understanding-Sonar-Data
but should be
https://github.com/awltech/sonar-data-migrator/wiki/i.-Understanding-Sonar-Data

_The other links have the same issue_

**Comment by verhagen** [comment]
Ok, issue already corrected.

**Comment by alpesh-shah** [comment]
Thanks for information, so I understand that I don't have any action for me :)

**Comment by verhagen** [comment]
✅  Indeed! _Initially I though I can't fix it myself, but then discovered how to make the correction!_
So fixed it for all the three links on the Wiki _Home_ page.
